@startuml

title Removal of Charging Rule

participant pgwU as "PCEF (PGW-U)"
participant pgwC as "PGW-C"
participant PCRF
participant OCS

PCRF -> pgwC : Policy and Charging Rules Provision (Gx RAR)
pgwC -> pgwU : Sx Session Modification Request [Remove PDR/FAR/URR]
pgwU -> pgwC : Sx Session Modification Response [Ack, Usage Report]
pgwC -> OCS  : PCEF Initiated Credit Request (Gy CCR-U) [Report Used Credits]
OCS -> pgwC  : Credit Response (Gy CCA) [Ack]
pgwC -> PCRF : Acknowledgment session Modification (Gx RAA)

@enduml
