swagger: '2.0'
info:
  title: "erGW API"
  version: "1.0.0"
  description: "erGW API to interact with erGW"
  license:
    name: "GPL 2.0"
    url: "https://www.gnu.org/licenses/#GPL"
basePath: /api/v1
paths:
  /version:
    get:
      summary: get the erGW version
      responses:
        '200':
          description: 'returns version of the erGW'
          schema:
            $ref: '#/definitions/Version'
  /status:
    get:
      summary: get the status
      responses:
        '200':
          description: returns the current status
          schema:
            $ref: '#/definitions/Status'
  /status/accept-new:
    get:
      summary: get the current 'accept-new' status
      responses:
        '200':
          description: get the current 'accept-new' status
          schema:
            $ref: '#/definitions/StatusAcceptNewRequests'
  /status/accept-new/{value}:
    post:
      summary: 'enables/disables accepting new requests'
      parameters:
        - name: value
          in: path
          required: true
          type: boolean
          description: 'true - accept new requests, false - do not accept new requests'
      responses:
        '200':
          description: returns the current 'accept-new' status
          schema:
            $ref: '#/definitions/StatusAcceptNewRequests'
  /metrics:
    get:
      summary: get the metrics
      responses:
        '200':
          description: returns the metrics
  /contexts:
    get:
      summary: 'get TEIDs of contexts by IMSI'
      parameters:
        - name: imsi
          in: query
          required: true
          type: integer
          default: 111111111111111
          description: 'list of related TEIDs'
      responses:
        '200':
          description: return list of TEIDs
          schema:
            $ref: '#/definitions/GetContextsTeids'
    delete:
      summary: 'delete all contexts'
      responses:
        '200':
          description: return count of contexts
          schema:
            $ref: '#/definitions/DeleteContexts'
  /contexts/{count}:
    delete:
      summary: 'delete N contexts'
      parameters:
        - name: count
          in: path
          required: true
          type: integer
          description: 'number of contexts for deleting'
      responses:
        '200':
          description: return count of contexts
          schema:
            $ref: '#/definitions/DeleteContexts'
definitions:
  Status:
    type: "object"
    properties:
      acceptNewRequests:
        type: "boolean"
        default: true
      nodeId:
        $ref:
          "#/definitions/Fqdn"
      plmnId:
        $ref:
          "#/definitions/PLMN"
  DeleteContexts:
    type: "object"
    properties:
      contexts:
        type: "integer"
        default: 0
  GetContextsTeids:
    type: "object"
    properties:
      teids:
        type: "array"
        items:
          type: integer
          default: 3416802480
  PLMN:
    type: "object"
    properties:
      mcc:
        type: "string"
      mnc:
        type: "string"
  StatusAcceptNewRequests:
    type: "object"
    properties:
      acceptNewRequests:
        type: "boolean"
  Version:
    type: "object"
    properties:
      version:
        type: "string"
  Fqdn:
    description: Fully Qualified Domain Name
    type: "string"
