name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:
  test:
    name: CI
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: [22.3.4.14, 23.0.4, 23.1.5.0, 23.2.1.0]
    container:
      image: erlang:${{ matrix.otp }}-alpine
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
           apk update
           apk --no-cache upgrade
           apk --no-cache add gcc git libc-dev libc-utils libgcc linux-headers make bash musl-dev musl-utils ncurses-dev pcre2 pkgconf scanelf wget zlib
    - name: Build
      run: rebar3 compile
    - name: Prep for tests
      run: |
           sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
           ip addr add fd96:dcd2:efdb:41c3::10/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::11/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::12/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::13/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::14/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::15/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::16/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::17/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::18/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::19/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::1a/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::20/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::30/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::40/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::50/64 dev lo
    - name: Run tests
      run: |
           rebar3 do xref
           rebar3 do ct
           rebar3 as test do coveralls send || /bin/true
    - name: Archive Test Output
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-output-${{ matrix.otp }}
        path: |
          _build/test/logs/
          !_build/test/logs/last
