name: quay.io

on: push

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Expire Labels
        id: expire
        run: |
          case ${{ github.ref }} in
            refs/tags/*) export EXPIRE="";;
            *)           export EXPIRE="quay.expires-after=7d";;
          esac
          echo ::set-output name=expire::${EXPIRE}
          echo ::set-output name=sha::$(git rev-parse --short HEAD)
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/travelping/ergw-c-node
          # add git short SHA as Docker tag
          tags: |
            type=ref,event=branch,suffix=-${{ steps.expire.outputs.sha }}
            type=semver,pattern={{version}}
          labels: |
            ${{ steps.expire.outputs.expire }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER_ID }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
